# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-08 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_assess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Roll_no', models.IntegerField()),
                ('Maths', models.IntegerField()),
                ('IAS', models.IntegerField()),
                ('HCI', models.IntegerField()),
                ('SE', models.IntegerField()),
                ('SC', models.IntegerField()),
                ('IR', models.IntegerField()),
            ],
        ),
    ]
