# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_assess', '0003_auto_20170108_1030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
