# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stud_assess', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_No', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('MQ1', models.IntegerField()),
                ('MQ2', models.IntegerField()),
                ('MQ3', models.IntegerField()),
                ('ML', models.IntegerField()),
                ('EQ1', models.IntegerField()),
                ('EQ2', models.IntegerField()),
                ('EQ3', models.IntegerField()),
                ('EQ4', models.IntegerField()),
                ('EL', models.IntegerField()),
                ('Assignment', models.FloatField()),
                ('Project', models.FloatField()),
            ],
        ),
    ]
