# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_assess', '0005_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Roll_No',
            field=models.CharField(max_length=10),
        ),
    ]
